### PR TITLE
Multistage dockerfile

### PR DESCRIPTION
**Pull request by MikkelHJuul**
By applying this commit you remove the unnecessary added extra tools from the docker image you build.  Therefore a base alpine container with only `scc` and your endpoint is left

The old Dockerfile add extra layers - 1: apk update (indices), 2: wget (3: bash I guess you personally want that for some reason?), 4: scc zipped, 5:  another version of scc, without execute permissions

The proposed Dockerfile has two layers on top of alpine,  scc and entrypoint.sh, down form 7.

The improvements make it a faster to download the container for instance in a pipeline. 

You could also remove the entrypoint.sh and just do 
```Dockerfile 
ENTRYPOINT ["/scc"]
```
You could probably even do a (but that will break ci)
```Dockerfile 
FROM scratch 
```
Although you could do a from scratch container on a specific tag, eg. `scratch` for a convenient way to run scc from your pc: `docker run -t -v some/folder:/dir -w /dir iryanbell/scc-docker-action:scratch`
(if you don't want to install it)

### CODE REVIEW

**Comment by MikkelHJuul** [comment]
I wrote this pull request on my phone,  you should not blindly add it. Try it out and do `docker image inspect`

**Comment by iRyanBell** [comment]
> I wrote this pull request on my phone, you should not blindly add it. Try it out and do `docker image inspect`

I appreciate the PR! I'll test locally and confirm.

**Comment by MikkelHJuul** [comment]
You could maybe also just do something like
```Dockerfile 
FROM golang as builder
RUN go get -u github.com/boyter/scc

FROM alpine
COPY --from=builder /go/../scc /scc
ENTRYPOINT ["scc"]
```
But I don't know about versions etc and how that i managed when doing this

**Comment by iRyanBell** [comment]
Both proposals fail during build. Please feel to _test_ and PR.

**Pull request closed without merging**
