### PR TITLE
Multistage Dockerfile

### PR DESCRIPTION
**Pull request by MikkelHJuul**
without typo and without entrypoint

Same as before, I only fixed the typo I had, and I tested it.

There is a short comment on the fact that this is a 32 bit vers. of scc running an amd64 image... but that is a whole other discussion.

### CODE REVIEW

**Comment by iRyanBell** [comment]
> without typo and without entrypoint
> 
> Same as before, I only fixed the typo I had, and I tested it.
> 
> There is a short comment on the fact that this is a 32 bit vers. of scc running an amd64 image... but that is a whole other discussion.

Please test before adding a PR. This fails with `Error: Docker build failed with exit code 8`

**Comment by MikkelHJuul** [comment]
> > without typo and without entrypoint
> > Same as before, I only fixed the typo I had, and I tested it.
> > There is a short comment on the fact that this is a 32 bit vers. of scc running an amd64 image... but that is a whole other discussion.
> 
> Please test before adding a PR. This fails with `Error: Docker build failed with exit code 8`

My apologies, after testing I copied the content, but the link (long line) was shortened with EOL-marker '$'

**Comment by iRyanBell** [comment]
> > > without typo and without entrypoint
> > > Same as before, I only fixed the typo I had, and I tested it.
> > > There is a short comment on the fact that this is a 32 bit vers. of scc running an amd64 image... but that is a whole other discussion.
> > 
> > 
> > Please test before adding a PR. This fails with `Error: Docker build failed with exit code 8`
> 
> My apologies, after testing I copied the content, but the link (long line) was shortened with EOL-marker '$'

Thank you for this PR. It looks like the API documentation will need a usage revision for compatibility with this merge -- the current configuration is described at: https://github.com/iRyanBell/scc-docker-action

Pulling this branch and running the previous configuration throws:
Error log

Future versions should also remain compatible with output, as requested here: https://github.com/iRyanBell/scc-docker-action/issues/2.

**Comment by MikkelHJuul** [comment]
> > > > without typo and without entrypoint
> > > > Same as before, I only fixed the typo I had, and I tested it.
> > > > There is a short comment on the fact that this is a 32 bit vers. of scc running an amd64 image... but that is a whole other discussion.
> > > 
> > > 
> > > Please test before adding a PR. This fails with `Error: Docker build failed with exit code 8`
> > 
> > 
> > My apologies, after testing I copied the content, but the link (long line) was shortened with EOL-marker '$'
> 
> Thank you for this PR. It looks like the API documentation will need a usage revision for compatibility with this merge -- the current configuration is described at: https://github.com/iRyanBell/scc-docker-action
> 
> Specifically, this is currently:
> 
> ```
> - name: Get the lines of code.
>     id: scc
>     uses: iryanbell/scc-docker-action@v1.0.2
>     with:
>         args: ${{ env.workspace }} -i js,go,html,css
> ```
> 
> Pulling this branch and running the previous configuration throws:
> Error log
> 
> Future versions should also remain compatible with the expected output, as requested here: #2.

I tested the container locally
mju@1b5svp2:~/open_source/ryan-bell-scc$ docker run -it -v /home/me/some_project/:/tmp/workdir -w /tmp/workdir <image> -i js,go,css,html
::set-output name=scc::───────────────────────────────────────────────────────────────────────────────%0ALanguage                 Files     Lines   Blanks  Comments     Code Complexity%0A───────────────────────────────────────────────────────────────────────────────%0A───────────────────────────────────────────────────────────────────────────────%0ATotal                        0         0        0         0        0          0%0A───────────────────────────────────────────────────────────────────────────────%0AEstimated Cost to Develop $0%0AEstimated Schedule Effort 0.000000 months%0AEstimated People Required 1 Grandparent%0A───────────────────────────────────────────────────────────────────────────────%0A
mju@1b5svp2:~/open_source/ryan-bell-scc$ 

is this fine ?

**Comment by iRyanBell** [comment]
The ideal test is to run the action and confirm that the output contains the lines of code information (perhaps we could automate this with another action?)

1. Create a GitHub project
2. Add the WIP action at `.github/workflows/scc-docker/action`
3. Call the action from `.github/workflows/main.yml` using something like:

```
- name: Get the lines of code.
  id: scc
  uses: ./.github/workflows/scc-docker-action
  with:
    args: ${{ env.workspace }} -i js,go,html,css
```

Push a commit to your project. Check the output from the action.

**Pull request closed without merging**
